------------------------------------------------
Repo description: Unnamed repository; edit this file 'description' to name the repository.
Repo active branch is pydev
Remote named "origin" with URL "https://github.com/CERN/TIGRE.git"
Last commit for repo is e2fa2cf9c23f32e538ec72598339f9337732b294.e2fa2cf9c23f32e538ec72598339f9337732b294
"test to logfile created. fixed some bugs these tests revealed." by reuben (rllindroos@gmail.com)
2019-02-21 17:05:52+00:00
count: 454 and size: 269
------------------------------------------------
GEOMETRY used for instance of testandlog: 
nVoxel: [ 32  64 128]
angles: None
rotDetector: [0 0 0]
sDetector: [32 64]
offOrigin: [0 0 0]
nDetector: [32 64]
filter: None
DSO: 32.0
mode: parallel
dVoxel: [1 1 1]
sVoxel: [ 32  64 128]
n_proj: None
accuracy: 0.5
DSD: 64.0
offDetector: [0 0]
dDetector: [1 1]
------------------------------------------------
SIRT Mon Feb 25 13:20:41 2019
nproj: 100 niter: 10
spherical projection: True
total time taken: 1.282161
------------------------------------------------
CGLS Mon Feb 25 13:20:43 2019
nproj: 100 niter: 10
spherical projection: True
ERROR at 13:20:43
Traceback (most recent call last):
  File "/home/reuben/TIGRE/Python/tests/testforlog.py", line 76, in testandlog
    res = getattr(algs, alg)(proj, geo, angles, niter=niter)
  File "/home/reuben/TIGRE/Python/tigre/algorithms/iterative_recon_alg.py", line 352, in iterativereconalg
    alg.run_main_iter()
  File "/home/reuben/TIGRE/Python/tigre/algorithms/conjugate_gradient_algorithms.py", line 88, in run_main_iter
    self.__p__ = s + beta * self.__p__
RuntimeWarning: invalid value encountered in multiply

------------------------------------------------
FBP Mon Feb 25 13:20:43 2019
nproj: 100 niter: 10
spherical projection: True
total time taken: 0.063645
------------------------------------------------
